### ISSUE TITLE
Incompatible with macOS

### ISSUE THREAD

**Issue by riverbend305** [ax-va/PyOpenGL-Pygame-Stemkoski-Pascale-2021#5]
The code within the py3d hierarchy is incompatible with macOS.  Most issues are related to the use of several  OpenGL keywords:
•	GL.glLineWidth() only supports a width of 1 on macOS but many examples use a width > 1 which must all be changed to avoid  throwing an error.  A fix also requires changing all ‘lineWidth’ parameter values to ‘1’. Better to universally use ‘1’ as a default and let non-mac platforms increase the width if they desire to do so?
•	Mac’s OpenGL deprecates GL_POINT_SMOOTH and its use must be commented out to avoid ‘py3d/material/point.pypy3d/material/point.py’ throwing an error. The fix is:
		        # if self._setting_dict["roundedPoints"]:
         		#     GL.glEnable(GL.GL_POINT_SMOOTH)
         		# else:
         		#     GL.glDisable(GL.GL_POINT_SMOOTH)

•	Mac’s OpenGL also deprecates ‘ texture2D’ and replaces the command with the ’ texture’ keyword.  Use of ‘ texture2D’  will throw an error in the ‘fragment_shader_code’ and ’ ‘texture’ cannot be used  as a variable name. An  example fix for ‘py3d/effects/template.py’  is:
		diff -r -w py3d.github/effects/template.py py3d/effects/template.py
		21c21
		<         uniform sampler2D texture;
		---
		>         uniform sampler2D texture1;
		26c26
		<             vec4 color = texture2D(texture, UV);
		---
		>             vec4 color = texture(texture1, UV);
		31c31
		<         self.add_uniform("sampler2D", "texture", [None, 1])
		---
		>         self.add_uniform("sampler2D", "texture1", [None, 1])

•	The default background of pygame is RED not BLACK which can cause some example shapes to not be seen as a contrasting color. An example fix for ‘py3d/examples/example-2-01-empty-window.py’  is:

#!/usr/bin/python3
import OpenGL.GL as GL
import pathlib
import sys

package_dir = str(pathlib.Path(__file__).resolve().parents[2])
if package_dir not in sys.path:
    sys.path.insert(0, package_dir)
from py3d.core.base import Base

class Example(Base):
    def initialize(self):
        print("""
        Render a window
        """)
        print("Initializing program...")
 
        # specify color used when clearing
        GL.glClearColor(0.0, 0.0, 0.0, 1.0)

    def update(self):

        # reset color buffer with specified color
        GL.glClear(GL.GL_COLOR_BUFFER_BIT)

Example().run()

The configuration of my mac is : 
    macOS (10.15.7), 
    python == 3.9.15, 
    numpy==1.22.4,
    pygame==2.1.2,
    PyOpenGL==3.1.6,
    PyOpenGL-accelerate==3.1.5 ( version 3.1.6 couldn’t be installed via pip) 

    Vendor: ATI Technologies Inc.
    Renderer: AMD Radeon Pro 560 OpenGL Engine
    OpenGL version supported: 4.1 ATI-3.10.23
    GLSL version supported: 4.10

**Comment by ax-va** [comment]
Hi! Thank you for your comments. I tested the code only on Windows and Ubuntu, but not  on MacOS. Usually, the OpenGL standard should be same on all supported platforms. But some deviations are possible depending on platforms, renderers, and drivers. I can suggest to update drivers and packages used to last versions and see whether that can solve the problems above.

**Comment by riverbend305** [comment]
It is my understanding that Apple is no longer updating the OpenGL library for macOS. 
Instead they are advocating Metal 3:
https://developer.apple.com/metal/

I could try compiling OpenGL from source files but I have already modified all of source files in your project and they all seem to operate as intended ( to the best I can gather ).
I will send you a tarball  of the modified files if you wish to check if the mods work for Windows and Ubuntu.

**Comment by kennethinfante** [comment]
@riverbend305 Can i ask where do I find the code examples that you edited? I'm going to try it as well

**Comment by riverbend305** [comment]
I update all the SW:
python3 == 3.10.8
numpy==1.23.4

pygame==2.1.2

PyOpenGL==3.1.6

PyOpenGL-accelerate==3.1.6

All of the issues remain. Attached is my changes to your code.
Regards,-Joe
    On Tuesday, November 15, 2022, 04:05:26 PM EST, Alexander Vasiliev ***@***.***> wrote:  
 
 


Hi! Thank you for your comments. I tested the code only on Windows and Ubuntu, but not on MacOS. Usually, the OpenGL standard should be same on all supported platforms. But some deviations are possible depending on platforms, renderers, and drivers. I can suggest to update drivers and packages used to last versions and see whether that can solve the problems above.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>
  
diff -r -w py3d.github/effects/additive_blend.py py3d/effects/additive_blend.py
21c21
<         uniform sampler2D texture;
---
>         uniform sampler2D texture1;
29,30c29,30
<             vec4 originalColor = texture2D(texture, UV);
<             vec4 blendColor = texture2D(blendTexture, UV);
---
>             vec4 originalColor = texture(texture1, UV);
>             vec4 blendColor = texture(blendTexture, UV);
36c36
<         self.add_uniform("sampler2D", "texture", [None, 1])
---
>         self.add_uniform("sampler2D", "texture1", [None, 1])
diff -r -w py3d.github/effects/bright_filter.py py3d/effects/bright_filter.py
21c21
<         uniform sampler2D texture;
---
>         uniform sampler2D texture1;
27c27
<             vec4 color = texture2D(texture, UV);
---
>             vec4 color = texture(texture1, UV);
34c34
<         self.add_uniform("sampler2D", "texture", [None, 1])
---
>         self.add_uniform("sampler2D", "texture1", [None, 1])
diff -r -w py3d.github/effects/color_reduce.py py3d/effects/color_reduce.py
22c22
<         uniform sampler2D texture;
---
>         uniform sampler2D texture1;
28c28
<             vec4 color = texture2D(texture, UV);
---
>             vec4 color = texture(texture1, UV);
35c35
<         self.add_uniform("sampler2D", "texture", [None, 1])
---
>         self.add_uniform("sampler2D", "texture1", [None, 1])
diff -r -w py3d.github/effects/horizontal_blur.py py3d/effects/horizontal_blur.py
21c21
<         uniform sampler2D texture;
---
>         uniform sampler2D texture1;
34c34
<                 averageColor += texture2D(texture, UV + offsetUV) * weight;
---
>                 averageColor += texture(texture1, UV + offsetUV) * weight;
41c41
<         self.add_uniform("sampler2D", "texture", [None, 1])
---
>         self.add_uniform("sampler2D", "texture1", [None, 1])
diff -r -w py3d.github/effects/invert.py py3d/effects/invert.py
22c22
<         uniform sampler2D texture;
---
>         uniform sampler2D texture1;
27c27
<             vec4 color = texture2D(texture, UV);
---
>             vec4 color = texture(texture1, UV);
33c33
<         self.add_uniform("sampler2D", "texture", [None, 1])
---
>         self.add_uniform("sampler2D", "texture1", [None, 1])
diff -r -w py3d.github/effects/pixelate.py py3d/effects/pixelate.py
22c22
<         uniform sampler2D texture;
---
>         uniform sampler2D texture1;
31c31
<             vec4 color = texture2D(texture, newUV);
---
>             vec4 color = texture(texture1, newUV);
36c36
<         self.add_uniform("sampler2D", "texture", [None, 1])
---
>         self.add_uniform("sampler2D", "texture1", [None, 1])
diff -r -w py3d.github/effects/template.py py3d/effects/template.py
21c21
<         uniform sampler2D texture;
---
>         uniform sampler2D texture1;
26c26
<             vec4 color = texture2D(texture, UV);
---
>             vec4 color = texture(texture1, UV);
31c31
<         self.add_uniform("sampler2D", "texture", [None, 1])
---
>         self.add_uniform("sampler2D", "texture1", [None, 1])
diff -r -w py3d.github/effects/tint.py py3d/effects/tint.py
23c23
<         uniform sampler2D texture;
---
>         uniform sampler2D texture1;
28c28
<             vec4 color = texture2D(texture, UV);
---
>             vec4 color = texture(texture1, UV);
34c34
<         self.add_uniform("sampler2D", "texture", [None, 1])
---
>         self.add_uniform("sampler2D", "texture1", [None, 1])
diff -r -w py3d.github/effects/vertical_blur.py py3d/effects/vertical_blur.py
21c21
<         uniform sampler2D texture;
---
>         uniform sampler2D texture1;
34c34
<                 averageColor += texture2D(texture, UV + offsetUV) * weight;
---
>                 averageColor += texture(texture1, UV + offsetUV) * weight;
41c41
<         self.add_uniform("sampler2D", "texture", [None, 1])
---
>         self.add_uniform("sampler2D", "texture1", [None, 1])
diff -r -w py3d.github/effects/vignette.py py3d/effects/vignette.py
25c25
<         uniform sampler2D texture;
---
>         uniform sampler2D texture1;
33c33
<             vec4 color = texture2D(texture, UV);
---
>             vec4 color = texture(texture1, UV);
48c48
<         self.add_uniform("sampler2D", "texture", [None, 1])
---
>         self.add_uniform("sampler2D", "texture1", [None, 1])
diff -r -w py3d.github/examples/example-2-01-empty-window.py py3d/examples/example-2-01-empty-window.py
1a2
> import OpenGL.GL as GL
15c16,18
<     """ Render a window """
---
>     print(""" 
>     Render a window 
>     """)
18a22,24
>         # specify color used when clearing
>         GL.glClearColor(0.0, 0.0, 0.0, 1.0)
> 
20c26,28
<         pass
---
> 
>         # reset color buffer with specified color
>         GL.glClear(GL.GL_COLOR_BUFFER_BIT)
diff -r -w py3d.github/examples/example-2-02-single-point.py py3d/examples/example-2-02-single-point.py
15d14
< 
17d15
<     """ Render a single point """
18a17,19
>         print(""" 
>         Render a single point 
>         """)
19a21
> 
37a40,43
> 
>         # specify color used when clearing
>         GL.glClearColor(0.0, 0.0, 0.0, 1.0)
> 
45a52,54
>         # reset color buffer with specified color
>         GL.glClear(GL.GL_COLOR_BUFFER_BIT)
> 
diff -r -w py3d.github/examples/example-2-03-hexagon.py py3d/examples/example-2-03-hexagon.py
18d17
<     """ Render six points in a hexagon arrangement """
19a19,21
>         print("""
>         Render six points in a hexagon arrangement 
>         """)
38c40,44
<         GL.glLineWidth(4)
---
>         GL.glLineWidth(1)
> 
>         # specify color used when clearing
>         GL.glClearColor(0.0, 0.0, 0.0, 1.0)
> 
53a60,63
> 
>         # reset color buffer with specified color
>         GL.glClear(GL.GL_COLOR_BUFFER_BIT)
> 
diff -r -w py3d.github/examples/example-2-04-shapes.py py3d/examples/example-2-04-shapes.py
18d17
<     """ Render two shapes """
19a19,21
>         print(""" 
>         Render two shapes 
>         """)
38c40,44
<         GL.glLineWidth(4)
---
>         GL.glLineWidth(1)
> 
>         # specify color used when clearing
>         GL.glClearColor(0.0, 0.0, 0.0, 1.0)
> 
59a66,69
> 
>         # reset color buffer with specified color
>         GL.glClear(GL.GL_COLOR_BUFFER_BIT)
> 
diff -r -w py3d.github/examples/example-2-05-hexagon-with-vertex-colors.py py3d/examples/example-2-05-hexagon-with-vertex-colors.py
18d17
<     """ Render shapes with vertex colors """
19a19,21
>         print("""
>         Render shapes with vertex colors 
>         """)
44c46,50
<         GL.glLineWidth(4)
---
>         GL.glLineWidth(1)
> 
>         # specify color used when clearing
>         GL.glClearColor(0.0, 0.0, 0.0, 1.0)
> 
67a74,77
> 
>         # reset color buffer with specified color
>         GL.glClear(GL.GL_COLOR_BUFFER_BIT)
> 
diff -r -w py3d.github/examples/example-2-06-two-triangles.py py3d/examples/example-2-06-two-triangles.py
19d18
<     """ Render two triangles with different positions and colors """
20a20,22
>         print(""" 
>         Render two triangles with different positions and colors 
>         """)
40a43,46
> 
>         # specify color used when clearing
>         GL.glClearColor(0.0, 0.0, 0.0, 1.0)
> 
61a68,71
> 
>         # reset color buffer with specified color
>         GL.glClear(GL.GL_COLOR_BUFFER_BIT)
> 
diff -r -w py3d.github/examples/example-2-07-animation-1.py py3d/examples/example-2-07-animation-1.py
19d18
<     """ Animate a triangle moving across screen """
20a20,22
>         print(""" 
>         Animate a triangle moving across screen 
>         """)
diff -r -w py3d.github/examples/example-2-08-animation-2.py py3d/examples/example-2-08-animation-2.py
20d19
<     """ Animate a triangle moving in a circular path around the origin """
21a21,23
>         print("""
>         Animate a triangle moving in a circular path around the origin 
>         """)
diff -r -w py3d.github/examples/example-2-09-color-changing.py py3d/examples/example-2-09-color-changing.py
20d19
<     """ Animate a triangle changing its color """
21a21,23
>         print(""" 
>         Animate a triangle changing its color 
>         """)
diff -r -w py3d.github/examples/example-2-10-keys-down-up-press.py py3d/examples/example-2-10-keys-down-up-press.py
1a2
> import OpenGL.GL as GL
16c17,20
<     """ Create a text-based application to verify that the key press works as expected """
---
>     print("""
>     Create a text-based application to verify that the key press works as expected.
>     Press and release 'space' or 'right' key.
>     """)
19a24,26
>         # specify color used when clearing
>         GL.glClearColor(0.0, 0.0, 0.0, 1.0)
> 
20a28,31
> 
>         # reset color buffer with specified color
>         GL.glClear(GL.GL_COLOR_BUFFER_BIT)
> 
diff -r -w py3d.github/examples/example-2-11-key-control.py py3d/examples/example-2-11-key-control.py
19d18
<     """ Enables the user to move a triangle using the arrow keys """
20a20
>         print(""" Enables the user to move a triangle using the arrow keys """)
diff -r -w py3d.github/examples/example-3-global-and-local-transformations.py py3d/examples/example-3-global-and-local-transformations.py
21c21,22
<     """
---
>     def initialize(self):
>         print("""
24,25c25
<     """
<     def initialize(self):
---
>     	""")
26a27
>        
diff -r -w py3d.github/examples/example-4-1-spinning-cube.py py3d/examples/example-4-1-spinning-cube.py
22d21
<     """ Render a basic scene that consists of a spinning cube """
23a23,25
>         print(""" 
>         Render a basic scene that consists of a spinning cube 
>         """)
diff -r -w py3d.github/examples/example-4-2-custom-geometry.py py3d/examples/example-4-2-custom-geometry.py
21d20
<     """ Render a basic scene that consists of a custom geometry """
22a22,24
>         print(""" 
>         Render a basic scene that consists of a custom geometry 
>         """)
diff -r -w py3d.github/examples/example-4-3-sine.py py3d/examples/example-4-3-sine.py
23c23,25
<     """ Render the sine function """
---
>     print(""" 
>     Render the sine function 
>     """)
57c59
<         point_material = PointMaterial(vs_code, fs_code, {"baseColor": [1, 1, 0], "pointSize": 10}, use_vertex_colors)
---
>         point_material = PointMaterial(vs_code, fs_code, {"baseColor": [1, 1, 0], "pointSize": 5}, use_vertex_colors)
59c61
<         line_material = LineMaterial(vs_code, fs_code, {"baseColor": [1, 0, 1], "lineWidth": 4}, use_vertex_colors)
---
>         line_material = LineMaterial(vs_code, fs_code, {"baseColor": [1, 0, 1], "lineWidth": 1}, use_vertex_colors)
diff -r -w py3d.github/examples/example-4-4-sphere.py py3d/examples/example-4-4-sphere.py
21d20
<     """ Render a spinning sphere with gradient colors """
22a22,24
>         print(""" 
>         Render a spinning sphere with gradient colors 
>         """)
diff -r -w py3d.github/examples/example-4-5-rippling-effect.py py3d/examples/example-4-5-rippling-effect.py
21c21,22
<     """
---
>     def initialize(self):
>         print("""
24,25c25
<     """
<     def initialize(self):
---
>         """)
diff -r -w py3d.github/examples/example-4-6-axes-and-xy-grid.py py3d/examples/example-4-6-axes-and-xy-grid.py
23c23,24
<     """
---
>     def initialize(self):
>         print("""
26,27c27
<     """
<     def initialize(self):
---
>         """)
diff -r -w py3d.github/examples/example-4-7-box-on-grid.py py3d/examples/example-4-7-box-on-grid.py
25c25,26
<     """
---
>     def initialize(self):
>         print("""
28,29c29
<     """
<     def initialize(self):
---
>         """)
diff -r -w py3d.github/examples/example-5-01-textured-square.py py3d/examples/example-5-01-textured-square.py
22d21
<     """ Render a textured square """
23a23,25
>         print(""" 
>         Render a textured square 
>         """)
diff -r -w py3d.github/examples/example-5-02-textured-skysphere-and-grass.py py3d/examples/example-5-02-textured-skysphere-and-grass.py
25c25,26
<     """
---
>     def initialize(self):
>         print("""
28,29c29
<     """
<     def initialize(self):
---
>         """)
diff -r -w py3d.github/examples/example-5-03-rippling-effect-in-texture.py py3d/examples/example-5-03-rippling-effect-in-texture.py
22c22,23
<     """
---
>     def initialize(self):
>         print("""
25,26c26
<     """
<     def initialize(self):
---
>         """)
47c47
<             uniform sampler2D texture;
---
>             uniform sampler2D texture1;
55c55
<                 fragColor = texture2D(texture, shiftUV);
---
>                 fragColor = texture(texture1, shiftUV);
60c60
<         self.wave_material.add_uniform("sampler2D", "texture", [grid_texure.texture_ref, 1])
---
>         self.wave_material.add_uniform("sampler2D", "texture1", [grid_texure.texture_ref, 1])
diff -r -w py3d.github/examples/example-5-04-blending-between-textures.py py3d/examples/example-5-04-blending-between-textures.py
22c22,23
<     """
---
>     def initialize(self):
>         print("""
26,27c27
<     """
<     def initialize(self):
---
>         """)
56,57c56,57
<                 vec4 color1 = texture2D(texture1, UV);
<                 vec4 color2 = texture2D(texture2, UV);
---
>                 vec4 color1 = texture(texture1, UV);
>                 vec4 color2 = texture(texture2, UV);
diff -r -w py3d.github/examples/example-5-05-distorting-texture.py py3d/examples/example-5-05-distorting-texture.py
22d21
<     """ Distort a texture over time by using a RGB noise texture with pseudo-random uv-coordinates """
23a23,25
>         print(""" 
>         Distort a texture over time by using a RGB noise texture with pseudo-random uv-coordinates 
>         """)
53c55
<                 vec4 noiseValues = texture2D(rgbNoise, uvShift);
---
>                 vec4 noiseValues = texture(rgbNoise, uvShift);
55c57
<                 fragColor = texture2D(image, uvNoise);
---
>                 fragColor = texture(image, uvNoise);
diff -r -w py3d.github/examples/example-5-06-1-procedural-textures-smoothed-random.py py3d/examples/example-5-06-1-procedural-textures-smoothed-random.py
21c21,22
<     """
---
>     def initialize(self):
>         print("""
24,26c25
<     """
< 
<     def initialize(self):
---
>         """)
27a27
> 
diff -r -w py3d.github/examples/example-5-06-2-procedural-textures-clouds.py py3d/examples/example-5-06-2-procedural-textures-clouds.py
21c21,22
<     """
---
>     def initialize(self):
>         print("""
24,26c25
<     """
< 
<     def initialize(self):
---
>         """)
27a27
> 
diff -r -w py3d.github/examples/example-5-06-3-procedural-textures-lava.py py3d/examples/example-5-06-3-procedural-textures-lava.py
21,24d20
<     """
<     Generate a procedural fragment color by using uv-coordinates
<     and also clouds, lava, marble, and wood grain textures
<     """
26a23,26
>         print("""
>         Generate a procedural fragment color by using uv-coordinates
>         and also clouds, lava, marble, and wood grain textures
>         """)
27a28
> 
diff -r -w py3d.github/examples/example-5-06-4-procedural-textures-marble.py py3d/examples/example-5-06-4-procedural-textures-marble.py
21,24d20
<     """
<     Generate a procedural fragment color by using uv-coordinates
<     and also clouds, lava, marble, and wood grain textures
<     """
26a23,26
>         print("""
>         Generate a procedural fragment color by using uv-coordinates
>         and also clouds, lava, marble, and wood grain textures
>         """)
27a28
> 
diff -r -w py3d.github/examples/example-5-06-5-procedural-textures-wood-grain.py py3d/examples/example-5-06-5-procedural-textures-wood-grain.py
21,24d20
<     """
<     Generate a procedural fragment color by using uv-coordinates
<     and also clouds, lava, marble, and wood grain textures
<     """
26a23,26
>         print("""
>         Generate a procedural fragment color by using uv-coordinates
>         and also clouds, lava, marble, and wood grain textures
>         """)
27a28
> 
diff -r -w py3d.github/examples/example-5-07-text-texture.py py3d/examples/example-5-07-text-texture.py
22d21
<     """ Render a rotating rectangle with a text texture """
23a23,25
>         print(""" 
>         Render a rotating rectangle with a text texture 
>         """)
24a27
> 
diff -r -w py3d.github/examples/example-5-08-billboarding-by-look-at.py py3d/examples/example-5-08-billboarding-by-look-at.py
27c27,29
<     """
---
> 
>     def initialize(self):
>         print("""
31,32c33
<     """
<     def initialize(self):
---
>         """)
33a35
> 
diff -r -w py3d.github/examples/example-5-09-billboarding-by-spritesheet.py py3d/examples/example-5-09-billboarding-by-spritesheet.py
26c26,27
<     """
---
>     def initialize(self):
>         print("""
30,31c31
<     """
<     def initialize(self):
---
>         """)
32a33
> 
diff -r -w py3d.github/examples/example-5-10-heads-up-display.py py3d/examples/example-5-10-heads-up-display.py
27c27,28
<     """
---
>     def initialize(self):
>         print("""
31,32c32
<     """
<     def initialize(self):
---
>         """)
33a34
> 
diff -r -w py3d.github/examples/example-5-11-render-targets.py py3d/examples/example-5-11-render-targets.py
28c28,29
<     """
---
>     def initialize(self):
>         print("""
33,34c34
<     """
<     def initialize(self):
---
>         """)
35a36
> 
diff -r -w py3d.github/examples/example-5-12-1-postprocessing-color-tinting.py py3d/examples/example-5-12-1-postprocessing-color-tinting.py
27,29d26
<     """
<     Demonstrate color tinting: predominance of red
<     """
30a28,30
>         print("""
>         Demonstrate color tinting: predominance of red
>         """)
31a32
> 
diff -r -w py3d.github/examples/example-5-12-2-postprocessing-color-inversion.py py3d/examples/example-5-12-2-postprocessing-color-inversion.py
27,29c27
<     """
<     Demonstrate color inversion
<     """
---
> 
30a29,31
>         print("""
>         Demonstrate color inversion
>         """)
31a33
> 
diff -r -w py3d.github/examples/example-5-12-3-postprocessing-pixelation.py py3d/examples/example-5-12-3-postprocessing-pixelation.py
27,29c27
<     """
<     Demonstrate pixelation
<     """
---
> 
30a29,31
>         print("""
>         Demonstrate pixelation
>         """)
31a33
> 
diff -r -w py3d.github/examples/example-5-12-4-postprocessing-color-reducing.py py3d/examples/example-5-12-4-postprocessing-color-reducing.py
27,29c27
<     """
<     Demonstrate reducing colors
<     """
---
> 
30a29,31
>         print("""
>         Demonstrate reducing colors
>         """)
31a33
> 
diff -r -w py3d.github/examples/example-5-12-5-postprocessing-vignette.py py3d/examples/example-5-12-5-postprocessing-vignette.py
27,29c27
<     """
<     Demonstrate the vignette effect: reduced brightness towards the edges of an image
<     """
---
> 
30a29,31
>         print("""
>         Demonstrate the vignette effect: reduced brightness towards the edges of an image
>         """)
31a33
> 
diff -r -w py3d.github/examples/example-5-12-6-postprocessing-compound-effect.py py3d/examples/example-5-12-6-postprocessing-compound-effect.py
29c29,31
<     """
---
> 
>     def initialize(self):
>         print("""
32,33c34
<     """
<     def initialize(self):
---
>         """)
34a36
> 
63d64
<         self.postprocessor.add_effect(TintEffect(tint_color=[0, 1, 0]))
64a66
>         self.postprocessor.add_effect(TintEffect(tint_color=[0, 1, 0]))
diff -r -w py3d.github/examples/example-6-1-1-lighted-spheres.py py3d/examples/example-6-1-1-lighted-spheres.py
28c28,30
<     """
---
>     def initialize(self):
> 
>         print("""
39,40c41,42
<     """
<     def initialize(self):
---
>         """)
> 
diff -r -w py3d.github/examples/example-6-1-2-dynamical-lighting.py py3d/examples/example-6-1-2-dynamical-lighting.py
31c31,33
<     """
---
>     def initialize(self):
>  
>         print("""
41,42c43,44
<     """
<     def initialize(self):
---
>         """)
> 
diff -r -w py3d.github/examples/example-6-2-bump-mapping.py py3d/examples/example-6-2-bump-mapping.py
26d25
<     """ Bump mapping: combining color textures with normal map textures """
27a27
>         print(""" Bump mapping: combining color textures with normal map textures """)
53c53
<             property_dict={"bumpStrength": 1},
---
>             property_dict={"bumpStrength": 10},
diff -r -w py3d.github/examples/example-6-3-1-postprocessing-bright-filter.py py3d/examples/example-6-3-1-postprocessing-bright-filter.py
27,29d26
<     """
<     Demonstrate a bright-filter effect
<     """
30a28,30
>         print("""
>         Demonstrate a bright-filter effect
>         """)
diff -r -w py3d.github/examples/example-6-3-2-postprocessing-blur.py py3d/examples/example-6-3-2-postprocessing-blur.py
28,30d27
<     """
<     Demonstrate a blur effect
<     """
31a29,31
>         print("""
>         Demonstrate a blur effect
>         """)
diff -r -w py3d.github/examples/example-6-3-3-postprocessing-additive-blend.py py3d/examples/example-6-3-3-postprocessing-additive-blend.py
27c27,28
<     """
---
>     def initialize(self):
>         print("""
32,33c33
<     """
<     def initialize(self):
---
>         """)
diff -r -w py3d.github/examples/example-6-3-4-postprocessor-light-bloom.py py3d/examples/example-6-3-4-postprocessor-light-bloom.py
30c30,31
<     """
---
>     def initialize(self):
>         print("""
35,36c36
<     """
<     def initialize(self):
---
>         """)
diff -r -w py3d.github/examples/example-6-4-postprocessing-glow.py py3d/examples/example-6-4-postprocessing-glow.py
31c31,32
<     """
---
>     def initialize(self):
>         print("""
35,36c36
<     """
<     def initialize(self):
---
>         """)
diff -r -w py3d.github/examples/example-6-5-shadows.py py3d/examples/example-6-5-shadows.py
29,31d28
<     """
<     Render shadows using shadow pass by depth buffers for the directional light.
<     """
32a30,32
>         print("""
>         Render shadows using shadow pass by depth buffers for the directional light.
>         """)
diff -r -w py3d.github/examples/example-template.py py3d/examples/example-template.py
31d30
<     """ Example template """
32a32
>         print(""" Example template """)
44c44
<                 "lineWidth": 8
---
>                 "lineWidth": 1
diff -r -w py3d.github/extras/axes.py py3d/extras/axes.py
7c7
<     def __init__(self, axis_length=1, line_width=4, axis_colors=([1, 0, 0], [0, 1, 0], [0, 0, 1])):
---
>     def __init__(self, axis_length=1, line_width=1, axis_colors=([1, 0, 0], [0, 1, 0], [0, 0, 1])):
diff -r -w py3d.github/extras/postprocessor.py py3d/extras/postprocessor.py
48c48
<         effect.uniform_dict["texture"].data[0] = target.texture.texture_ref
---
>         effect.uniform_dict["texture1"].data[0] = target.texture.texture_ref
diff -r -w py3d.github/material/flat.py py3d/material/flat.py
98c98
<             uniform sampler2D texture;
---
>             uniform sampler2D texture1;
106c106
<                     color *= texture2D(texture, UV);
---
>                     color *= texture(texture1, UV);
diff -r -w py3d.github/material/lambert.py py3d/material/lambert.py
23c23
<             self.add_uniform("sampler2D", "texture", [texture.texture_ref, 1])
---
>             self.add_uniform("sampler2D", "texture1", [texture.texture_ref, 1])
143c143
<             uniform sampler2D texture;
---
>             uniform sampler2D texture1;
176c176
<                     color *= texture2D( texture, UV );
---
>                     color *= texture( texture1, UV );
181c181
<                     calcNormal += bumpStrength * vec3(texture2D(bumpTexture, UV));
---
>                     calcNormal += bumpStrength * vec3(texture(bumpTexture, UV));
195c195
<                     float closestDistanceToLight = texture2D(shadow0.depthTexture, shadowCoord.xy).r;
---
>                     float closestDistanceToLight = texture(shadow0.depthTexture, shadowCoord.xy).r;
diff -r -w py3d.github/material/phong.py py3d/material/phong.py
23c23
<             self.add_uniform("sampler2D", "texture", [texture.texture_ref, 1])
---
>             self.add_uniform("sampler2D", "texture1", [texture.texture_ref, 1])
157c157
<             uniform sampler2D texture;
---
>             uniform sampler2D texture1;
190c190
<                     color *= texture2D( texture, UV );
---
>                     color *= texture( texture1, UV );
195c195
<                     calcNormal += bumpStrength * vec3(texture2D(bumpTexture, UV));
---
>                     calcNormal += bumpStrength * vec3(texture(bumpTexture, UV));
209c209
<                     float closestDistanceToLight = texture2D(shadow0.depthTexture, shadowCoord.xy).r;
---
>                     float closestDistanceToLight = texture(shadow0.depthTexture, shadowCoord.xy).r;
diff -r -w py3d.github/material/point.py py3d/material/point.py
19,22c19,23
<         if self._setting_dict["roundedPoints"]:
<             GL.glEnable(GL.GL_POINT_SMOOTH)
<         else:
<             GL.glDisable(GL.GL_POINT_SMOOTH)
---
> 
>         # if self._setting_dict["roundedPoints"]:
>         #     GL.glEnable(GL.GL_POINT_SMOOTH)
>         # else:
>         #     GL.glDisable(GL.GL_POINT_SMOOTH)
diff -r -w py3d.github/material/sprite.py py3d/material/sprite.py
50c50
<             uniform sampler2D texture;
---
>             uniform sampler2D texture1;
55c55
<                 vec4 color = vec4(baseColor, 1) * texture2D(texture, UV);
---
>                 vec4 color = vec4(baseColor, 1) * texture(texture1, UV);
64c64
<         self.add_uniform("sampler2D", "texture", [texture.texture_ref, 1])
---
>         self.add_uniform("sampler2D", "texture1", [texture.texture_ref, 1])
diff -r -w py3d.github/material/texture.py py3d/material/texture.py
26c26
<             uniform sampler2D texture;
---
>             uniform sampler2D texture1;
31c31
<                 vec4 color = vec4(baseColor, 1.0) * texture2D(texture, UV);
---
>                 vec4 color = vec4(baseColor, 1.0) * texture(texture1, UV);
39c39
<         self.add_uniform("sampler2D", "texture", [texture.texture_ref, 1])
---
>         self.add_uniform("sampler2D", "texture1", [texture.texture_ref, 1])

**Comment by riverbend305** [comment]
MacOS mods:

[py3d.tar.gz](https://github.com/ax-va/PyOpenGL-Pygame-Stemkoski-Pascale-2021/files/10024448/py3d.tar.gz)

Anyone else has my permission to create a fork with this code.

**Comment by ax-va** [comment]
I added testing configurations in the description. I think you have some problems with the OpenGL realization (Metal) for MacOS. You can fork the project and add changes for MacOS.

**Comment by ax-va** [comment]
It can also be that the GL version of 4.1 ist not enough to execute the code successfully

**Comment by riverbend305** [comment]
texture2D() is deprecated as of (at least) OpenGL 3.3; see page 99 of the 3.30 GLSL specification (https://registry.khronos.org/OpenGL/specs/gl/GLSLangSpec.3.30.pdf) . It will continue to be supported in OpenGL compatibility profiles to avoid breaking existing code, but its usage in new code is strongly discouraged.

**Comment by ax-va** [comment]
You are right. I have replaced function texture2D by texture and variable texture by textureSampler. Thank you!
