### ISSUE TITLE
Add a Ring

### ISSUE THREAD

**Issue by happyleibniz** [ax-va/PyOpenGL-Pygame-Stemkoski-Pascale-2021#7]
I'm trying to make a black hole but i can't code the RingGeometry, can you help?
![Screenshot 2024-06-01 145203](https://github.com/ax-va/PyOpenGL-Pygame-Stemkoski-Pascale-2021/assets/121920485/a511ae9c-10ac-4a1f-8e6a-45a8e21c8e91)

**Comment by ax-va** [comment]
What is a ring? There is a cylinder.

**Comment by happyleibniz** [comment]
<img width="286" alt="Untitled" src="https://github.com/ax-va/PyOpenGL-Pygame-Stemkoski-Pascale-2021/assets/121920485/29661ae1-b012-4d9c-9e1e-aae36c58ab00">
some thing like this

**Comment by ax-va** [comment]
Describe the ring using a parametric equation.

**Comment by happyleibniz** [comment]
<math xmlns="http://www.w3.org/1998/Math/MathML" display="block"><semantics><mtable rowspacing="0.25em" columnalign="right left" columnspacing="0em"><mtr><mtd><mstyle scriptlevel="0" displaystyle="true"><mrow><mi>x</mi><mo stretchy="false">(</mo><mi>t</mi><mo stretchy="false">)</mo></mrow></mstyle></mtd><mtd><mstyle scriptlevel="0" displaystyle="true"><mrow><mrow></mrow><mo>=</mo><mi>r</mi><mi>cos</mi><mo>⁡</mo><mo stretchy="false">(</mo><mi>t</mi><mo stretchy="false">)</mo></mrow></mstyle></mtd></mtr><mtr><mtd><mstyle scriptlevel="0" displaystyle="true"><mrow><mi>y</mi><mo stretchy="false">(</mo><mi>t</mi><mo stretchy="false">)</mo></mrow></mstyle></mtd><mtd><mstyle scriptlevel="0" displaystyle="true"><mrow><mrow></mrow><mo>=</mo><mi>r</mi><mi>sin</mi><mo>⁡</mo><mo stretchy="false">(</mo><mi>t</mi><mo stretchy="false">)</mo></mrow></mstyle></mtd></mtr></mtable><annotation encoding="application/x-tex">\begin{align*}
x(t) &amp;= r \cos(t) \\
y(t) &amp;= r \sin(t)
\end{align*}
</annotation></semantics></math>

**Comment by happyleibniz** [comment]
<math xmlns="http://www.w3.org/1998/Math/MathML" display="block"><semantics><mtable rowspacing="0.25em" columnalign="right left" columnspacing="0em"><mtr><mtd><mstyle scriptlevel="0" displaystyle="true"><mrow><mi>x</mi><mo stretchy="false">(</mo><mi>t</mi><mo stretchy="false">)</mo></mrow></mstyle></mtd><mtd><mstyle scriptlevel="0" displaystyle="true"><mrow><mrow></mrow><mo>=</mo><mi>r</mi><mi>cos</mi><mo>⁡</mo><mo stretchy="false">(</mo><mi>t</mi><mo stretchy="false">)</mo></mrow></mstyle></mtd></mtr><mtr><mtd><mstyle scriptlevel="0" displaystyle="true"><mrow><mi>y</mi><mo stretchy="false">(</mo><mi>t</mi><mo stretchy="false">)</mo></mrow></mstyle></mtd><mtd><mstyle scriptlevel="0" displaystyle="true"><mrow><mrow></mrow><mo>=</mo><mi>r</mi><mi>sin</mi><mo>⁡</mo><mo stretchy="false">(</mo><mi>t</mi><mo stretchy="false">)</mo></mrow></mstyle></mtd></mtr></mtable><annotation encoding="application/x-tex">\begin{align*}
x(t) &amp;= r \cos(t) \\
y(t) &amp;= r \sin(t)
\end{align*}
</annotation></semantics></math>

**Comment by happyleibniz** [comment]
x(t) = r cos(t)  y(t) = r sin(t)?

**Comment by ax-va** [comment]
I think you need two parameters. The first one changes t. The second one changes r. In the code, they are named as u and v. Good luck with your project. I close the issue.
